### PR TITLE
add NoPrompt for installation

### PR DESCRIPTION
**Pull request by MSLaaf**
This will allow automated build processes to proceed.

### CODE REVIEW

**Comment by morrownr** [comment]
Thanks. I wasn't thinking about automated builds. But you forgot to document it. I guess I get to do that?

**Comment by MSLaaf** [comment]
Yes i did forget that... ;

I can update the readme if you want me to do that... I just made it work ;-)

Maurice

**Comment by morrownr** [comment]
Maurice, I'll make a deal with you. If you document it in the README.md, I'll see about adding -h and --help support.

**Comment by MSLaaf** [comment]
I can do both really, it's mostly cut'n paste ;-)

**Pull request merged**
